/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeedAnalyzerRouteImport } from './routes/seed-analyzer'
import { Route as IndexRouteImport } from './routes/index'

const SeedAnalyzerRoute = SeedAnalyzerRouteImport.update({
  id: '/seed-analyzer',
  path: '/seed-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seed-analyzer': typeof SeedAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seed-analyzer': typeof SeedAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seed-analyzer': typeof SeedAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seed-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seed-analyzer'
  id: '__root__' | '/' | '/seed-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeedAnalyzerRoute: typeof SeedAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seed-analyzer': {
      id: '/seed-analyzer'
      path: '/seed-analyzer'
      fullPath: '/seed-analyzer'
      preLoaderRoute: typeof SeedAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeedAnalyzerRoute: SeedAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
